### ISSUE TITLE
Several warnings including "fastText not configured"

### ISSUE THREAD

**Issue by lpla** [meyayl/docker-languagetool#38] opened 2024-08-01 06:22 UTC
Hi. I just updated to the latest Docker image from a couple of hours ago. Just checked the logs and these are the lines that appear, showing some relevant warnings related to the ngram model and fastText:

```
2024-08-01 08:19:12 INFO: User "languagetool" alread has has uid 783.
2024-08-01 08:19:12 INFO: Group "languagetool" already has gid 783.
2024-08-01 08:19:12 WARNING: No base path for ngram language modules provided, skipping download of none.
2024-08-01 08:19:12 INFO: "langtool_fasttextModel" not specified. Skipping download of fasttext model.
2024-08-01 08:19:12 INFO: Creating new LanguageTool config file.
2024-08-01 08:19:12 INFO: Version Informations:
2024-08-01 08:19:12   Alpine Linux v3.20.2
2024-08-01 08:19:12   openjdk 21.0.4 2024-07-16 LTS
2024-08-01 08:19:12   OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
2024-08-01 08:19:12   OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
2024-08-01 08:19:12 INFO: Using following LanguageTool configuration:
2024-08-01 08:19:12   fasttextBinary=/usr/bin/fasttext
2024-08-01 08:19:12 INFO: Using JAVA_OPTS=-Xms256m -Xmx1024m -XX:+UseSerialGC
2024-08-01 08:19:12 2024-08-01 06:19:12.528 GMT INFO  org.languagetool.server.DatabaseAccessOpenSource Not setting up database access, dbDriver is not configured
2024-08-01 08:19:12 2024-08-01 06:19:12 +0000 WARNING: running in HTTP mode, consider running LanguageTool behind a reverse proxy that takes care of encryption (HTTPS)
2024-08-01 08:19:12 2024-08-01 06:19:12 +0000 WARNING: running in public mode, LanguageTool API can be accessed without restrictions!
2024-08-01 08:19:12 2024-08-01 06:19:12 +0000 Setting up thread pool with 10 threads
2024-08-01 08:19:13 2024-08-01 06:19:13.262 GMT WARN  org.languagetool.language.identifier.DefaultLanguageIdentifier fastText not configured - language detection performance will be degraded. See https://dev.languagetool.org/http-server#starting-from-command-line for instructions.
2024-08-01 08:19:13 2024-08-01 06:19:13.266 GMT INFO  org.languagetool.server.TextChecker A/B-Test enabled: []
2024-08-01 08:19:13 2024-08-01 06:19:13 +0000 Starting LanguageTool 6.4 (build date: 2024-03-28 14:05:28 +0100, 0e9362b) server on http://localhost:8010...
2024-08-01 08:19:13 2024-08-01 06:19:13 +0000 Server started
```

**Comment by meyayl** [comment] 2024-08-02 05:56
Please share the output of `docker inspect {containername}`, so I can understand how you configured the container.
Without understanding how you container is configured, the logs are worth nothing.

**Comment by lpla** [comment] 2024-08-02 07:30
I created the container with all default settings, only with the port redirect 8081:8010. See the output of the command:

```
> docker inspect clever_cohen
[
    {
        "Id": "bb912933fae534a4dbdc1134eb15c73631164a562599dadcf98ed321522e3486",
        "Created": "2024-08-01T06:19:11.787167322Z",
        "Path": "/sbin/tini",
        "Args": [
            "-g",
            "-e 143",
            "--",
            "/entrypoint.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 771,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-08-02T06:19:39.015592654Z",
            "FinishedAt": "2024-08-01T13:00:59.894399502Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2024-08-02T07:25:54.943589109Z",
                        "End": "2024-08-02T07:25:54.967605161Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-02T07:26:25.059101Z",
                        "End": "2024-08-02T07:26:25.080927767Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-02T07:26:55.16353693Z",
                        "End": "2024-08-02T07:26:55.185472338Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-02T07:27:25.271244063Z",
                        "End": "2024-08-02T07:27:25.294534385Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-02T07:27:55.38648041Z",
                        "End": "2024-08-02T07:27:55.410127076Z",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:ead6e26571314b2e23c18fbcde7f3c0ee9ed151cf5e335e34c4022546b5e64d5",
        "ResolvConfPath": "/var/lib/docker/containers/bb912933fae534a4dbdc1134eb15c73631164a562599dadcf98ed321522e3486/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/bb912933fae534a4dbdc1134eb15c73631164a562599dadcf98ed321522e3486/hostname",
        "HostsPath": "/var/lib/docker/containers/bb912933fae534a4dbdc1134eb15c73631164a562599dadcf98ed321522e3486/hosts",
        "LogPath": "/var/lib/docker/containers/bb912933fae534a4dbdc1134eb15c73631164a562599dadcf98ed321522e3486/bb912933fae534a4dbdc1134eb15c73631164a562599dadcf98ed321522e3486-json.log",
        "Name": "/clever_cohen",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8010/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8081"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/58df90060a5d69a8c867c318e2435005ed5b38e4a79188f79f8d5b0b56a7cc6e-init/diff:/var/lib/docker/overlay2/f3a4f4cb9a24ec52712093b1687b793ac1ac8d17843dffc20928c9de10117284/diff:/var/lib/docker/overlay2/01eabcd65f58df930f0c289e03f18bbb66d17e38ab0805fb2676520bc8b69355/diff:/var/lib/docker/overlay2/126f70dbab6d4469387b97aa8ade738ae7d9889833930b4d5968de6274ba79da/diff:/var/lib/docker/overlay2/8c3fb2ecab5856cd2a2876d9392bc5fbd097f7133a8e49fe3055ce6a0ca8d9e5/diff:/var/lib/docker/overlay2/31e1943bef6265a91e016bc1037ac0c96316fc0e96c8d7e68243397ce58df32a/diff:/var/lib/docker/overlay2/453c98f2756c53527af3f4ddd9d494057fa0ced1cf9e4fef0d59a1fbd94554f9/diff:/var/lib/docker/overlay2/611933f28542ec575a0ebd960c476c8e7c7e3503225ca9c398a96a939c80a8cc/diff:/var/lib/docker/overlay2/5b6eec5b5a8dc997f2652613f92b6c6f3d54af164e73783c9412750607300f72/diff",
                "MergedDir": "/var/lib/docker/overlay2/58df90060a5d69a8c867c318e2435005ed5b38e4a79188f79f8d5b0b56a7cc6e/merged",
                "UpperDir": "/var/lib/docker/overlay2/58df90060a5d69a8c867c318e2435005ed5b38e4a79188f79f8d5b0b56a7cc6e/diff",
                "WorkDir": "/var/lib/docker/overlay2/58df90060a5d69a8c867c318e2435005ed5b38e4a79188f79f8d5b0b56a7cc6e/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "bb912933fae5",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8010/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/java/customjre/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "JAVA_HOME=/opt/java/customjre",
                "langtool_fasttextBinary=/usr/bin/fasttext",
                "download_ngrams_for_langs=none",
                "MAP_UID=783",
                "MAP_GID=783",
                "LOG_LEVEL=INFO",
                "LOGBACK_CONFIG=./logback.xml"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "wget --quiet --post-data \"language=en-US\u0026text=a simple test\" -O - http://localhost:8010/v2/check \u003e /dev/null 2\u003e\u00261  || exit 1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000,
                "StartPeriod": 10000000000
            },
            "Image": "meyay/languagetool:latest",
            "Volumes": null,
            "WorkingDir": "/languagetool",
            "Entrypoint": [
                "/sbin/tini",
                "-g",
                "-e 143",
                "--",
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "544ded8ada4481cf4390803a392cf4af03ebd9d00271f56dba4fd790b10c8e76",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8010/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8081"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/544ded8ada44",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "bb69bcb053a2a34947c877176ef5caf6624376479d0ab5af81abdc21747b3d47",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "02:42:ac:11:00:02",
                    "NetworkID": "094331c9aa5bea40408011feb203c1635edc087e5f3ba222d777f51ba7f385a6",
                    "EndpointID": "bb69bcb053a2a34947c877176ef5caf6624376479d0ab5af81abdc21747b3d47",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by meyayl** [comment] 2024-08-03 08:23
Whatever tool you used for the update: it completely killed the container configuration. What you see is the result of either a bug of that tool, or wrong usage of it.

Please delete the container a new container using either the `docker run` command or compose file as described in the README.md.

**Comment by lpla** [comment] 2024-08-03 10:26
I simply used "Run" in the Docker Desktop interface to create a new container with the updated image, and the only setting I changed was the port mapping. 

I will check that command line does not bork the configuration and try to update the Docker Desktop software when I get to the office next month. Thank you.

**Comment by meyayl** [comment] 2024-08-06 21:28
Welcome!

I am closing the issue, as the issue was caused by non-existing configuration of the container

**Comment by meyayl** [comment] 2024-09-15 12:06
Let me quote a sentence of my 2nd response:
> Please delete the container, and create a new container using either the `docker run` command or compose file as described in the README.md.
Your inspect output shows that you ignored what I wrote.

I tested in Docker Desktop v4.34.2 and configured only the port mapping, like you did.

This is the output:
```
2024-09-15 13:52:49 INFO: "langtool_fasttextModel" not specified. Skipping download of fasttext model.
2024-09-15 13:52:49 INFO: Creating new LanguageTool config file.
2024-09-15 13:52:49 INFO: Version Informations:
2024-09-15 13:52:49   Alpine Linux v3.20.3
2024-09-15 13:52:49   openjdk 21.0.4 2024-07-16 LTS
2024-09-15 13:52:49   OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
2024-09-15 13:52:49   OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
2024-09-15 13:52:49 INFO: Using following LanguageTool configuration:
2024-09-15 13:52:49   fasttextBinary=/usr/bin/fasttext
2024-09-15 13:52:49 INFO: Using JAVA_OPTS=-Xms256m -Xmx1024m -XX:+UseSerialGC
2024-09-15 13:52:49 2024-09-15 11:52:49.749 GMT INFO  org.languagetool.server.DatabaseAccessOpenSource Not setting up database access, dbDriver is not configured
2024-09-15 13:52:49 2024-09-15 11:52:49 +0000 WARNING: running in HTTP mode, consider running LanguageTool behind a reverse proxy that takes care of encryption (HTTPS)
2024-09-15 13:52:49 2024-09-15 11:52:49 +0000 WARNING: running in public mode, LanguageTool API can be accessed without restrictions!
2024-09-15 13:52:49 2024-09-15 11:52:49 +0000 Setting up thread pool with 10 threads
2024-09-15 13:52:50 2024-09-15 11:52:50.768 GMT WARN  org.languagetool.language.identifier.DefaultLanguageIdentifier fastText not configured - language detection performance will be degraded. See https://dev.languagetool.org/http-server#starting-from-command-line for instructions.
2024-09-15 13:52:50 2024-09-15 11:52:50.773 GMT INFO  org.languagetool.server.TextChecker A/B-Test enabled: []
2024-09-15 13:52:50 2024-09-15 11:52:50 +0000 Starting LanguageTool 6.4 (build date: 2024-03-28 14:05:28 +0100, 0e9362b) server on http://localhost:8010...
2024-09-15 13:52:50 2024-09-15 11:52:50 +0000 Server started
```
The WARNING entries are unpreventable with the public available version of LanguageTool.
The log entry with WARN regarding fasttext is because without configuring a path for the fasttext model, the fasttext model will not exist.

It doesn't make any sense to use the image like this without any ngrams model and the fasttext model, you fall back to whatever is included in the ~300MB LanguageTool release. The English ngrams model alone has roughly 15GB...  

I am not sure what else I can do that make you understand that the container needs to be configured to provide any value.

Note: the languageTool server only provides an API, there is no UI whatsoever. Please check the https://languagetool.org/ homepage for available plugins.

**Closed by meyayl** 2024-09-15 12:06 UTC
